-- Drop table

-- DROP TABLE DW.modelo_capsa.FT_LINEA_GESTION_ECONOMICA

CREATE TABLE DW.modelo_capsa.FT_LINEA_GESTION_ECONOMICA (
	sk_escenario int NOT NULL,
	sk_version int NOT NULL,
	sk_fecha int NOT NULL,
	sk_periodo int NOT NULL,
	sk_unidad_contable int NULL,
	sk_centro int NULL,
	sk_cuenta int NOT NULL,
	sk_empresa int NOT NULL,
	sk_negocio int NOT NULL,
	sk_division int NOT NULL,
	sk_departamento int NOT NULL,
	sk_actividad int NOT NULL,
	sk_unidad_negocio int NULL,
	sk_unidad_contable_origen int NULL,
	sk_proyecto int NOT NULL,
	sk_activo int NOT NULL,
	sk_activo_tipo int NULL,
	sk_articulo int NOT NULL,
	sk_almacen int NOT NULL,
	sk_ente int NOT NULL,
	sk_equipo int NOT NULL,
	debito_credito  varchar(255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	tipo_movimiento varchar(255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	monto_origen numeric(18,0) NULL,
	sk_moneda_origen int NOT NULL,
	unidades_fisicas_origen numeric(18,0) NULL,
	sk_unidad_medida_origen int NOT NULL,
	unitario_origen numeric(18,0) NULL,
	desc_linea_asiento varchar(255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	tc_origen_a_ARS numeric(18,0) NULL,
	ponderador_polinomica_01 numeric(18,0) NULL,
	ponderador_polinomica_02 numeric(18,0) NULL,
	ponderador_polinomica_03 numeric(18,0) NULL,
	ponderador_polinomica_04 numeric(18,0) NULL,
	ponderador_polinomica_05 numeric(18,0) NULL,
	unidades_fisicas_unificada numeric(18,0) NULL,
	sk_unidad_medida_unificada int NOT NULL,
	sk_moneda_consulta int NOT NULL,
	unitario_consulta numeric(18,0) NULL,
	monto_consulta numeric(18,0) NULL,
	desc_asiento varchar(255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	sk_fecha_contabilizacion int NOT NULL,
	fecha_recepcion_compromiso date NULL,
	sk_ot_ult_estado varchar(255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	sk_tipo_doc_oc int NOT NULL,
	nro_oc varchar(255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	linea_oc varchar(255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	nro_documento_asiento varchar(255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	sk_tipo_doc_asiento int NOT NULL,
	estado_documento_asiento varchar(255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	nro_batch_origen varchar(255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	tipo_batch_origen varchar(255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	desc_batch_origen varchar(255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	sk_proceso int NOT NULL,
	sk_usuario_imputacion int NOT NULL
)